site_name: HyDAMO Validatiehandboek
site_description: Documentatie voor de HyDAMO Validatietool, validatieregels en ondersteunende bestanden.
repo_url: https://github.com/HetWaterschapshuis/HyDAMOValidatiehandboek
repo_name: HetWaterschapshuis/HyDAMOValidatiehandboek

theme:
  name: material
  language: nl
  favicon: assets/favicon-hwh.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: orange

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Start:
      - Aan de slag: getting-started.md
      - Gebruikersregistratie: 02 Gebruikersregistratie.md
      - Known issues en tips: 03 Known issues en tips.md
      - Versie overzicht: 04 Versie overzicht.md
  - Validatieregels:
      - Bestanden en versies: resources.md
      - Basis validatieregels: 05 Basis validatieregels.md
      - Validatieregels bewerken: guides/edit_rules.md
  - Componenten:
      - Webclient:
          - Overzicht: 06 HyDAMO validatie Webclient.md
          - Starten en inloggen: HyDAMO validatie Webclient/01 Starten en inloggen.md
          - Opbouw van de schermen: HyDAMO validatie Webclient/02 Opbouw van de schermen.md
          - Beheren van validatietaken: HyDAMO validatie Webclient/03 Beheren van validatietaken.md
          - Kaartresultaten: HyDAMO validatie Webclient/04 Bekijken van validatie resultaten op een kaart.md
          - Tabelresultaten: HyDAMO validatie Webclient/05 Bekijken van validatie resultaten in tabel.md
      - API:
          - Overzicht: 07 HyDAMO validatie-API.md
          - API definitie: HyDAMO validatie-API/01 API definitie.md
          - Voorbeelden gebruik API: HyDAMO validatie-API/02 Voorbeelden gebruik API.md
      - Validatiemodule:
          - Overzicht: 08 HyDAMO Validatiemodule.md
          - Uitvoeren van een validatie: HyDAMO Validatiemodule/01 Uitvoeren van een validatie.md
          - Validatieregels: HyDAMO Validatiemodule/02 Validatieregels.md
          - Functies: HyDAMO Validatiemodule/Validatieregels/01 Functies.md
          - Resultaten: HyDAMO Validatiemodule/03 Resultaten.md
  - Ondersteuning:
      - HyDAMO Wasmachine: wasmachine.md
      - Mee-ontwikkelen: 09 Mee-ontwikkelen.md
      - Gebruikersmiddag: 10 Gebruikersmiddag HyDAMO Validatietool.md
